module 2: props and events (from jsbin)
robot-den/thinknetica_react pull request #2
Opened 2017-10-31 19:00 UTC by robot-den

для BlogsContainer и BlogList не стал описывать defaultProps, вроде бы нет смысла т.к. эти компоненты должны работать с массивом постов...

2017-11-01 08:50 UTC, blackleadsu requested changes

2017-11-01 08:50 UTC, blackleaden commented on BlogItem.js
> +  meta: {
DefaultProps не будут работать с вложенными в объект полями -- либо (если props.meta пуст) подставят весь объект, либо (если post.meta хоть `{}`) не сделают ничего. Так что рекомендую вынести metadata в отдельный компонент, как это сейчас c image.

2017-11-01 08:53 UTC, blackleadsu requested changes

2017-11-01 08:53 UTC, blackleaden commented on BlogItem.js
> +        <br/>
Использовать br для отступов блочных элементов... ай) Лучше строчку css написать;)

2017-11-01 08:53 UTC, blackleaden commented on BlogItem.js
> +  meta: {
Кстати, про description -- тоже не сработает. 
По поводу decription -- вложенность props.description.text избыточна. Зачем text?

2017-11-04 05:19 UTC, blackleadsu approved these changes

2017-11-04 11:38 UTC, merged