Module 4: develop environment
robot-den/thinknetica_react pull request #4
Opened 2017-11-19 15:59 UTC by robot-den

2017-11-24 02:37 UTC, blackleadsu requested changes

2017-11-24 02:37 UTC, blackleaden commented on src/components/blog/BlogItem.js
> +import Image from './post_elements/Image';
По поводу папки **post_elements**: 
* того же самого правильно создать папку `BlogItem` и сложить туда элементы из `post_elements`; 
* файл 'BlogItem.js' поместить в неё же и переименовать в `index.js`; 
* соответственно, переписать import'ы в этом `BlogItem/index.js` из `./post_elements/компонент` в `./компонент`.

И вот мы "инкапсулировали" элементы записи блога в папку, а запись (`BlogItem`) будет подключаться всё так же -- `import BlogItem from './BlogItem'`. Вебпак подключит индексный файл из папки BlogItem.
Круто, да? :)

2017-11-24 02:37 UTC, blackleaden commented on src/components/blog/PieChart.js
> +import React from 'react';
eslint ругается на этот файл:
* ты забыл сделать npm install **--save** c3
* линтер против деструктурирования в параметрах метода класса

P.S. посмотреть всё, что думает линтер о проекте можно через консоль: `./node_modules/eslint/bin/eslint.js ./src --ext js,jsx`

2017-11-24 02:37 UTC, blackleaden commented on src/components/blog/BlogsContainer.js
> +import React from 'react';
Контейнеры принято выделять в отдельную папку, отдельно от презентационных компонентов, наряду с папкой compontents, helpers, constants.

2017-11-26 05:21 UTC, blackleadsu approved these changes

2017-11-27 16:00 UTC, merged